### ISSUE TITLE
dSprites dataset

### ISSUE THREAD

**Issue by MoeinSorkhei** [visinf/adapter_plus#1]
Hello, I am unable to produce similar results to yours on dSprites dataset when finetuning. You have mentioned the that the dsprites_loc and dsprites_orientation tasks both have 16 classes, while in the original [repository](https://www.tensorflow.org/datasets/catalog/dsprites) it is mentioned they have 32 and 40 classes respectively.

Could you clarify how you select classes?
Can you perhaps provide code to do so?

**Comment by jmsteitz** [comment]
VTAB only utilizes orientation and x_position from dSprites with 16 classes each. The code to group classes can be found [here](https://github.com/google-research/task_adaptation/blob/d7630d3c43ba052b5a35546b312d9454a9f2c96b/task_adaptation/data/dsprites.py).
